#!/bin/bash -l

#$ -P rise-grid          # project
#$ -N preprocess        # job name
#$ -j y                 # merge stdout/stderr
#$ -o preprocess.qlog   # output log
#$ -l h_rt=12:00:00     # walltime, adjust as needed
#$ -pe omp 8            # CPU cores, matches num_workers in preprocess.py
#$ -l gpus=1            # request 1 GPU
#$ -l gpu_c=7.0         # min GPU compute capability
#$ -l gpu_type=A100     # request a specific GPU model, see `qgpus` for options

module load python3/3.10.12
module load cuda/12.2

cd "$SGE_O_WORKDIR"
pip install --user -r requirements.txt

python src/preprocess.py
